### ISSUE TITLE
Datapacks not being added to new worlds

### ISSUE THREAD

**Issue by BrekiTomasson** [Declipsonator/Global-Datapack#1]
Expected behavior using this mod is that any datapack added to `[game_directory]/datapacks` would be automatically loaded in any new world created, but that's not happening. `/datapack list` isn't even listing them.

Not sure why you're using `new File(FabricLoader.getInstance().getGameDir().toString() + "\\datapacks")` when you could just be using `Path`. Not tested, but something like `FabricLoader.getInstance().getGameDir().resolve("datapacks")` should work.

**Comment by Declipsonator** [comment]
I'm not really sure why the datapacks wouldn't load in, I just cloned this repo and it worked as expected. I will change `new File(FabricLoader.getInstance().getGameDir().toString() + "\\datapacks")` to path though.

**Comment by Declipsonator** [comment]
Just ran it using the jar on modrinth and worked there as well. You should make sure the datapacks you're putting in are valid.

**Comment by BrekiTomasson** [comment]
I assume you're running this on Windows? On Linux/Mac, the path `\\datapacks` will not work as those systems use `/` as path separators.

Edit: Yup, double-checked. Using the released version of this mod, I now have a folder in my installation called `minecraft\datapacks` - that's the actual name of the folder, not a `minecraft` folder with a subdirectory called `datapacks`. Fixing the path resolution should fix the problem, so I'll wait for the next release.

**Comment by Declipsonator** [comment]
Oh that makes a lot more sense, I'll recompile tomorrow and tell you when modrinth verifies it.

**Comment by BrekiTomasson** [comment]
v1.1 is working as intended! Thank you very much!

**Comment by Declipsonator** [comment]
No Problem!
