### ISSUE TITLE
Mod settings

### ISSUE THREAD

**Issue by BizCub** [Declipsonator/Global-Datapack#10]
Expected behavior of the mod: all packages given in a specific folder are loaded into the world and work immediately after the world is created. It makes sense to add a setting so that datapacks can be loaded, but they do not affect the world until the player turns them on. When I create a world, I don’t want it to change even before it’s created. And nothing can be done about it. If it's at all possible, could you do it?

**Comment by Declipsonator** [comment]
So what you would like is a setting where the datapacks are available but not enabled by default?

**Comment by BizCub** [comment]
Yes
