### ISSUE TITLE
[Suggestion] Datapack load order

### ISSUE THREAD

**Issue by mpustovoi** [Declipsonator/Global-Datapack#12]
This can be implemented by adding a configuration file to the `config` folder, in which the modpack author will write an array of datapacks names.
This could help with situations where it's necessary to override, for example, part of the functions of a datapack downloaded from Modrinth, with another custom datapack. Or maybe when one datapack is an add-on for another and the modpack author needs to make sure that the main one is loaded first.

**Comment by Declipsonator** [comment]
Hey, sorry for the late response I had to do some research. Global Datapacks loads datapacks the same way vanilla minecraft loads them which means there are a few ways to set priority:

### Naming
Datapacks are (by default) loaded alphabetically so you can rename the datapacks like so to order them:
1Thisdatapackloadsfirst.zip
2Thisdatapackloadssecond.zip
...

### Enable/Disable Command
You can also order them by disabling them and then enabling them like this:
`datapack enable <name> (first|last)`
`datapack enable <name> (before|after) <existing>`

Cheers!

**Comment by mpustovoi** [comment]
Sounds like a good option for a single override datapack.
However, when a modpack is downloaded from Modrinth, the default names of the datapacks are taken, and this cannot be changed in any way.
But thank you anyway.
