### ISSUE TITLE
available_datapacks dosen't work in 1.21.1

### ISSUE THREAD

**Issue by futamiy** [Declipsonator/Global-Datapack#14]
![image](https://github.com/user-attachments/assets/5b34749f-4066-445a-a9e6-7efcbbc10b35)
![image](https://github.com/user-attachments/assets/d23c2e37-6d23-4c1e-b760-e8ec612614d4)
![image](https://github.com/user-attachments/assets/92b300cb-a471-4da3-9ae1-99924cc1b8d6)

**Comment by Declipsonator** [comment]
Available datapacks and regular datapacks added through this mod can be accessed using the datapack command in-game. I'm closing this issue but feel free to create a new one with the datapack screen as a feature request.
